#!/bin/bash

## Remove Kubernetes Resources
kubectl delete deployment couchbase0{1..3}

kubectl delete persistentvolumeclaims couchbase0{1..3}

kubectl delete services couchebase0{1..3}

## Remove GCP Resources
gcloud container clusters delete -q couchbase

gcloud compute firewall-rules delete -q default-allow-couchbase
