apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: couchbase03
  labels:
    run: couchbase03
spec:
  replicas: 1
  selector:
    matchLabels:
      run: couchbase03
      app: couchbase
  template:
    metadata:
      labels:
        run: couchbase03
        app: couchbase
    spec:
      containers:
      - name: couchbase
        image: couchbase:community-4.5.1
        volumeMounts:
        - name: data
          mountPath: /opt/couchbase/var
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: couchbase03
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - couchbase
              topologyKey: "kubernetes.io/hostname"
