apiVersion: v1
kind: Service
metadata:
  name: couchbase03
  labels:
    run: couchbase03
spec:
  selector:
    run: couchbase03
  ports:
  - name: web       # 8091: Couchbase Web console, REST/HTTP interface
    port: 8091
  clusterIP: None
