apiVersion: v1
kind: Service
metadata:
  name: couchbase02
  labels:
    run: couchbase02
spec:
  selector:
    run: couchbase02
  ports:
  - name: web       # 8091: Couchbase Web console, REST/HTTP interface
    port: 8091
  clusterIP: None
