apiVersion: v1
kind: Service
metadata:
  name: couchbaselb03
  labels:
    run: couchbaselb03
spec:
  selector:
    run: couchbase03
  ports:
  - name: web       # 8091: Couchbase Web console, REST/HTTP interface
    port: 8091
  - name: xdcr      # 8092: Views, queries, XDCR
    port: 8092
  - name: query     # 8093: Query services (4.0+)
    port: 8093
  - name: full-text # 8094: Full-text Search (4.5+)
    port: 8094
  - name: data-ssl  # 11207: Smart client library data node access (SSL)
    port: 11207
  - name: bucket
    port: 11209
  - name: moxi      # 11210: Smart client library/moxi data node access
    port: 11210
  - name: data      # 11211: Legacy non-smart client library data node access
    port: 11211
  - name: incoming-ssl-proxy
    port: 11214
  - name: outgoing-ssl-proxy
    port: 11215
  - name: web-ssl   # 18091: Couchbase Web console, REST/HTTP interface (SSL)
    port: 18091
  - name: xdcr-ssl  # 18092: Views, query, XDCR (SSL)
    port: 18092
  - name: query-ssl # 18093: Query services (SSL) (4.0+)
    port: 18093
  - name: erlang
    port: 4369
  - name: otp
    port: 21101
  type: LoadBalancer
