apiVersion: v1
kind: Service
metadata:
  name: couchbase01
  labels:
    run: couchbase01
spec:
  selector:
    run: couchbase01
  ports:
  - name: web       # 8091: Couchbase Web console, REST/HTTP interface
    port: 8091
  clusterIP: None
